PROJ_NAME=main

ARDUINO_DIR=/home/emanuele/.local/share/umake/ide/arduino
TEENSY_CORE=$(ARDUINO_DIR)/hardware/teensy/avr/cores/teensy3

CC_NAME =   arm-none-eabi-gcc
LD_NAME =   $(CC_NAME)
AR_NAME =   arm-none-eabi-ar
AS_NAME =   arm-none-eabi-as
OBJCOPY_NAME    =   arm-none-eabi-objcopy

CC	=	arm-none-eabi-gcc
LD=$(LD_NAME)
AR=$(AR_NAME)
AS=$(AS_NAME)
OBJCOPY=$(OBJCOPY_NAME)

PROJ_DIR:=$(shell pwd)

_OBJS = $(wildcard $(PROJ_DIR)/*.c)
OBJS :=	$(addsuffix .o, $(basename $(_OBJS)))
#Compile flags
ASFLAGS=-g
LDFLAGS=	--specs=nosys.specs
CFLAGS= -c -O2 -g -Wall -ffunction-sections -nostdlib -MMD \
        -fno-exceptions	\
        -mthumb -mcpu=cortex-m4 -fsingle-precision-constant	\
        -D__MK20DX256__ -DF_CPU=72000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH	\
				-I$(TEENSY_CORE) -I$(PROJ_DIR)

all:	$(PROJ_NAME).elf

$(PROJ_NAME).elf: $(OBJS) $(PROJ_NAME).o
	$(CC)  -o $@ $(OBJS) $(CFLAGS)
	$(OBJCOPY) -O ihex $(PROJ_NAME).elf $(PROJ_NAME).hex
	$(OBJCOPY) -O binary $(PROJ_NAME).hex $(PROJ_NAME).bin

%.o: $(PROJ_DIR)/%.c $(PROJ_DIR)/%.h
	$(CC) -o $@ $(CFLAGS)
.PHONY: clean

clean:
	rm -f *.o *.elf *.bin *.list *.d *.hex

debug:
	$(info Found the following src files: $(OBJS))

	

